apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hls
  namespace: runai-{{ .Values.project.name }}
spec:
  ingressClassName: nginx
  rules:
    - host: hls.{{ .Values.cluster.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rtmp-server
                port:
                  number: 8080
